name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
authors: [timvisee, sgdc3, xephi, Metonymia]
version: ${project.version}
load: startup
api-version: 1.16
commands:
  dm:
    description: Dungeon Maze command
    usage: /dm
  dungeonmaze:
    description: Dungeon Maze command
    usage: /dungeonmaze
